- id: simplified_morning_wakeup_lighting_sequence
  alias: Simplified Morning Wake-Up Lighting Sequence
  description: Gradual wake-up lighting sequence from 8:00 AM to 9:00 AM
  triggers:
  - at: 07:45:00
    trigger: time
  actions:
  - target:
      entity_id: light.smart_light_24041085050865591001c4e7ae030df0
    data:
      brightness: 1
      color_temp_kelvin: 3000
      transition: 1500
    action: light.turn_on
  - delay: 00:00:05
  - target:
      entity_id: light.smart_light_24041085050865591001c4e7ae030df0
    data:
      brightness: 150
      color_temp_kelvin: 3000
      transition: 1500
    action: light.turn_on
  mode: single
