version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ./volumes/homeassistant:/config
    ports:
      - "8000:8123"  # Home Assistant web interface

  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon:latest
    restart: unless-stopped
    depends_on:
      - homeassistant
    environment:
      - TZ=${TZ:-UTC}
      - HA_URL=http://homeassistant:8123
      - TOKEN=${LONG_LIVE_HA_TOKEN}
      - DASH_URL=http://appdaemon:5050
    volumes:
      - ./volumes/appdaemon/conf:/conf
      - ./volumes/appdaemon/apps:/apps
    ports:
      - "8012:5050"  # AppDaemon web interface (Dashboard)

  octoprint:
    container_name: octoprint
    image: octoprint/octoprint
    restart: unless-stopped
    environment:
      - ENABLE_MJPG_STREAMER=true
    volumes:
      - ./volumes/octoprint:/octoprint
    ports:
      - "8001:5000"  # OctoPrint web interface
      - "8002:8080"  # MJPG-Streamer (if enabled)

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ./volumes/pihole/etc-pihole:/etc/pihole
      - ./volumes/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "53:53/tcp"     # DNS (keeping standard port for functionality)
      - "53:53/udp"     # DNS (keeping standard port for functionality)
      - "67:67/udp"     # DHCP (keeping standard port for functionality)
      - "8003:80"       # Pi-hole web interface
      - "8004:443"      # Pi-hole web interface (HTTPS)
    restart: unless-stopped

  rutorrent:
    container_name: rutorrent
    image: crazymax/rtorrent-rutorrent:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_AUTH_METHOD=none
    volumes:
      - ./volumes/rutorrent/data:/data
      - ./volumes/rutorrent/downloads:/downloads
    ports:
      - "8005:8080"     # Web UI HTTP
      - "8010:8000"    # SCGI external (mapped from internal 8000)
      - "50000:50000"  # DHT and incoming connections
      - "6881:6881"    # Standard BitTorrent port
      - "6881:6881/udp"# UDP tracker communications
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "8008:9000"    # Web interface
      - "8009:8000"    # Edge agent API
    restart: unless-stopped
