services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    privileged: true
    restart: unless-stopped
    environment:
      - TZ=${TZ:-UTC}
#      - PYTHONPATH=/usr/src/homeassistant
#      - PYTHONARGS=-Xfrozen_modules=off
    volumes:
      - /home/thomas/raspberry-pi-config/docker/volumes/homeassistant:/config
      - /home/thomas/dev/core:/usr/src/homeassistant
    ports:
      - "8000:8123"  # Home Assistant web interface
      - "5678:5678"  # Debug port

  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer:/data
    ports:
      - "8008:9000"    # Web interface
      - "8009:8000"    # Edge agent API
    restart: unless-stopped
